language: node_js

node_js:
- lts/fermium

before_install:
- openssl aes-256-cbc -K $encrypted_1a9d6c8ad656_key -iv $encrypted_1a9d6c8ad656_iv
  -in .secret.enc -out .secret -d

install:
- pip install awscli
- npm install

script:
- npx truffle compile

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: deploy
